from linkedlist2 import LinkedList
list1 = LinkedList()
list1.add("Tom")
list1.add("George")
list1.add("Peter")
list1.add("Jean")
list1.add("Jane")

list2 = []
list2.append("Tom")
list2.append("George")
list2.append("Michael")
list2.append("Michelle")
list2.append("Daniel")
print("Current list1")
print(list1)
print("After addAll is called")
list1.addAll(list2)
print(list1)
print("After removeAll is called")
list1.removeAll(list2)
print(list1)
print("After retain all is called")
list1.retainAll(list2)
print(list1)
